version: '3.1'

services:
  db:
    hostname: db
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pg-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8580:8080"
  ms1:
    image: tamerlanaghaev/ms1:1.0.f94d0ff
    restart: always
    ports:
      - "9091:8081"
    environment:
      - DB_CONNECTION_IP=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
  ms2:
    image: tamerlanaghaev/ms2:1.0.f94d0ff
    restart: always
    ports:
      - "9092:8082"
    environment:
      - DB_CONNECTION_IP=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
  reverse_proxy:
    image: nginx:latest
    hostname: proxy
    container_name: reverse_proxy
    depends_on:
      - ms1
      - ms2
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  pg-data:
